version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${CONTAINER_NAME}/data/mysql:/var/lib/mysql
    networks:
      - gruvetube_network

  web:
    image: python:3.11
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${DOCKER_PORT}:5000"
    volumes:
      - ${VIDEO_DOWNLOAD_PATH}:/app/data/videos
      - ${MUSIC_DOWNLOAD_PATH}:/app/data/music
    networks:
      - gruvetube_network
    depends_on:
      - db
    command: >
      sh -c "pip install -r requirements.txt &&
             python src/app.py"

networks:
  gruvetube_network:
    driver: bridge
